spring:
  datasource:
    url: jdbc:h2:tcp://localhost//Users/woony.kim/Desktop/woonys_github/blog-code/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type : trace